### ISSUE TITLE
migrating to 6.1.0 seems broken due to missing dependency

### ISSUE THREAD

**Issue by animegrafmays** [JohnXLivingston/peertube-plugin-livechat#150]
**Describe the bug**
upgrading from peertube-plugin-livechat 6.0 to 6.1.0 is broken

**To Reproduce**
1, click install update on admin panel
2. install fails

**Expected behavior**
upgrade completes without error

**Screenshots**

```
2023-02-03 14:21:59.825 warn: Cannot install plugin peertube-plugin-livechat. {
   "err": {
     "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage/plugins/node_modules/got/node_modules/decompress-response/index.js'\n    at Object.openSync (node:fs:585:3)\n    at Object.readFileSync (node:fs:453:35)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1122:18)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/got/dist/source/core/index.js:14:28)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/got/dist/source/as-promise/types.js:14:16)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/got/dist/source/as-promise/index.js:16:17)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)",
     "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage/plugins/node_modules/got/node_modules/decompress-response/index.js'",
     "errno": -2,
     "syscall": "open",
     "code": "ENOENT",
     "path": "/var/www/peertube/storage/plugins/node_modules/got/node_modules/decompress-response/index.js"
   }
}
```

**Server (please complete the following information):**
 - Ubuntu 20.04.4 LTS
 - Peertube version: 5.0.1
 - Peertube installation type: standard
 - peertube-plugin-livechat version: 6.1.0
 - Chat mode if relevant [disabled, Prosody, external XMPP, external]:

**Plugin diagnostic:**
N/A

**Additional context**
Peertube upgraded without issue and plugin was working fine until attempting to upgrade to 6.1.0

**Comment by animegrafmays** [comment]
I was able to get it to install by forcing a delete of the plugin via CLI tools, cleaning up the leftover directories that werent removed in peertube plugin's data folders and reinstalling. closing as it's been resolved
