### ISSUE TITLE
Cannot install 7.0.1

### ISSUE THREAD

**Issue by hjri** [JohnXLivingston/peertube-plugin-livechat#183]
**Describe the bug**

**To Reproduce**
1. Try to install livechat 7.0.1

**Expected behavior**
Plugin installed

**Screenshots**

**Server (please complete the following information):**
 - OS version [e.g. Debian 10, ...]: 
 - Peertube version: 5.1.0
 - Peertube installation type [e.g. standard, docker, ...]:  standard
 - peertube-plugin-livechat version: 7.0.1
 - Chat mode if relevant [disabled, Prosody, external XMPP, external]:

**Plugin diagnostic:**
If this is a server setup issue, please go to the plugin settings, click on «launch diagnostic», and copy/paste the result.
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Log:
```
info[6/6/2023, 9:16:50 PM] Successful installation of plugin peertube-plugin-livechat.
info[6/6/2023, 9:16:50 PM] Registering plugin or theme peertube-plugin-livechat.
error[6/6/2023, 9:16:50 PM] Cannot install plugin peertube-plugin-livechat, removing it...
{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage_local/plugins/node_modules/clone-response/node_modules/mimic-response/index.js'\n    at Object.openSync (node:fs:585:3)\n    at Object.readFileSync (node:fs:453:35)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1122:18)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage_local/plugins/node_modules/clone-response/src/index.js:4:23)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage_local/plugins/node_modules/cacheable-request/src/index.js:10:23)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage_local/plugins/node_modules/got/dist/source/core/index.js:13:26)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)",
    "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage_local/plugins/node_modules/clone-response/node_modules/mimic-response/index.js'",
    "errno": -2,
    "syscall": "open",
    "code": "ENOENT",
    "path": "/var/www/peertube/storage_local/plugins/node_modules/clone-response/node_modules/mimic-response/index.js"
  }
}
info[6/6/2023, 9:16:50 PM] Uninstalling plugin peertube-plugin-livechat.
info[6/6/2023, 9:16:50 PM] Unregister plugin peertube-plugin-livechat.
warn[6/6/2023, 9:16:50 PM] Cannot unregister plugin peertube-plugin-livechat.
{
  "err": {
    "stack": "Error: Unknown plugin peertube-plugin-livechat to unregister\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/plugins/plugin-manager.js:206:23)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:167:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:163:16)\n    at PluginManager.unregister (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/plugins/plugin-manager.js:202:24)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/plugins/plugin-manager.js:287:28)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:167:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:163:16)\n    at PluginManager.uninstall (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/plugins/plugin-manager.js:284:24)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/plugins/plugin-manager.js:254:32)\n    at Generator.throw (<anonymous>)\n    at rejected (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:165:69)",
    "message": "Unknown plugin peertube-plugin-livechat to unregister"
  }
}
info[6/6/2023, 9:16:51 PM] Plugin peertube-plugin-livechat uninstalled.
warn[6/6/2023, 9:16:51 PM] Cannot install plugin peertube-plugin-livechat.
{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage_local/plugins/node_modules/clone-response/node_modules/mimic-response/index.js'\n    at Object.openSync (node:fs:585:3)\n    at Object.readFileSync (node:fs:453:35)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1122:18)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage_local/plugins/node_modules/clone-response/src/index.js:4:23)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage_local/plugins/node_modules/cacheable-request/src/index.js:10:23)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/peertube/storage_local/plugins/node_modules/got/dist/source/core/index.js:13:26)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)",
    "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage_local/plugins/node_modules/clone-response/node_modules/mimic-response/index.js'",
    "errno": -2,
    "syscall": "open",
    "code": "ENOENT",
    "path": "/var/www/peertube/storage_local/plugins/node_modules/clone-response/node_modules/mimic-response/index.js"
  }
}
```
Trying to manually run `yarn` in clone-response and then installing livechat causes its node_modules to be wiped

**Comment by hjri** [comment]
ok nevermind restarting peertube fixed it
