### ISSUE TITLE
Cannot install plugin, missing Node module file with apparently buggy path

### ISSUE THREAD

**Issue by TeknikalDomain** [JohnXLivingston/peertube-plugin-livechat#93]
**Describe the bug**
Attempting to (re-install) livechat version 5.5.0 on PeerTube version 4.1.0 fails with error `ENOENT: no such file or directory, open '/var/www/peertube/storage/plugins/node_modules/express-http-proxy/node_modules/raw-body/index.js'`.

**To Reproduce**
1. (Unknown if related) Uninstall livechat if not already removed
2. Attempt to install livechat plugin
3. Be told it cannot be installed

**Expected behavior**
The plugin should install successfully

**Screenshots**
No screenshots can help, but here's the full message from the logs:

```
{
    "level": "warn",
    "message": "Cannot install plugin peertube-plugin-livechat.",
    "label": "vids.tekdmn.me:443",
    "err": {
        "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage/plugins/node_modules/express-http-proxy/node_modules/inherits/inherits.js'
            at Object.openSync (node:fs:585:3)\n    at Object.readFileSync (node:fs:453:35)
            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:18)
            at Module.load (node:internal/modules/cjs/loader:981:32)
            at Function.Module._load (node:internal/modules/cjs/loader:822:12)
            at Module.require (node:internal/modules/cjs/loader:1005:19)
            at require (node:internal/modules/cjs/helpers:102:18)
            at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/express-http-proxy/node_modules/http-errors/index.js:18:16)
            at Module._compile (node:internal/modules/cjs/loader:1103:14)
            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
            at Module.load (node:internal/modules/cjs/loader:981:32)
            at Function.Module._load (node:internal/modules/cjs/loader:822:12)
            at Module.require (node:internal/modules/cjs/loader:1005:19)
            at require (node:internal/modules/cjs/helpers:102:18)
            at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/express-http-proxy/node_modules/raw-body/index.js:17:19)
            at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
            at Module.load (node:internal/modules/cjs/loader:981:32)
            at Function.Module._load (node:internal/modules/cjs/loader:822:12)
            at Module.require (node:internal/modules/cjs/loader:1005:19)
            at require (node:internal/modules/cjs/helpers:102:18)
            at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/express-http-proxy/lib/requestOptions.js:5:18)
            at Module._compile (node:internal/modules/cjs/loader:1103:14)
            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
            at Module.load (node:internal/modules/cjs/loader:981:32)
            at Function.Module._load (node:internal/modules/cjs/loader:822:12)
            at Module.require (node:internal/modules/cjs/loader:1005:19)
            at require (node:internal/modules/cjs/helpers:102:18)",
        "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage/plugins/node_modules/express-http-proxy/node_modules/inherits/inherits.js'",
        "errno": -2,
        "syscall": "open",
        "code": "ENOENT",
        "path": "/var/www/peertube/storage/plugins/node_modules/express-http-proxy/node_modules/inherits/inherits.js"
    },
    "timestamp": "2022-03-03T05:04:19.369Z"
}
```

**Server (please complete the following information):**
 - OS version: Ubuntu 20.04
 - Peertube version: 4.1.0
 - Peertube installation type: standard 
 - peertube-plugin-livechat version: 5.5.0

**Additional context**
- Interesting that the path here has `node_modules` twice. I'm not a JS dev, but I don't think it looks right for a Node package *itself* to contain a `node_modules` folder.
- Also that stack trace is rather repetitive... looks like something got caught in a loop somewhere?

**Comment by JohnXLivingston** [comment]
> Attempting to (re-install) livechat version 5.5.0 on PeerTube version 4.1.0 fails with error `ENOENT: no such file or directory, open '/var/www/peertube/storage/plugins/node_modules/express-http-proxy/node_modules/raw-body/index.js'`.

I cannot reproduce the bug. I tried several uninstall/re-install: it worked every time on my instance.

> * Interesting that the path here has `node_modules` twice. I'm not a JS dev, but I don't think it looks right for a Node package _itself_ to contain a `node_modules` folder.

That's not a problem. Node will look go through directories and use the first version found for each required modules.

Have you recently updated ubuntu, node or yarn?
What are your node and yarn versions?
Have you tried restarting peertube (after uninstalling the plugin), and then try to install it again?
Any other error/warning log before this one?
In the file `/var/www/peertube/storage/plugins/node_modules/express-http-proxy/package.json`, what is the version of this package? On my server, I have no `inherits` folder in this module, but I don't have this bug.
Have you other plugins installed?
Can you list me directories in `/var/www/peertube/storage/plugins/node_modules`?

**Comment by TeknikalDomain** [comment]
Okay, let's take these one by one.

> Have you recently updated ubuntu, node or yarn?
Ubuntu gets weekly updates through my management system, I believe both Node and Yarn are in the repos.

> What are your node and yarn versions?
```
# node --version
v16.14.0
# yarn --version
1.22.10
```
> Have you tried restarting peertube (after uninstalling the plugin), and then try to install it again?
.....yes... and it did nothing. Today, I restart and try again just for good measure, **and it works.**

I am honestly done trying to understand software, none of this makes sense.

**Comment by JohnXLivingston** [comment]
> I am honestly done trying to understand software, none of this makes sense.

Totally agree....

Glad to know that it works now.
